image: node:18

pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - apt-get update && apt-get install -y zip
            - npm install --legacy-peer-deps
            - npm run build
            - zip -r app.zip .next package.json next.config.js public
          artifacts:
            - app.zip

      - step:
          name: Upload
          script:
            - mkdir artifact
            - cp app.zip artifact
            - pipe: atlassian/ftp-deploy:0.4.1
              variables:
                USER: $REMOTE_USER
                PASSWORD: $REMOTE_PASSWORD
                SERVER: $REMOTE_SERVER
                REMOTE_PATH: /bitbucket-artifact-bw/
                LOCAL_PATH: ${BITBUCKET_CLONE_DIR}/artifact/

      - step:
          name: Deploy
          script:
            - pipe: atlassian/ssh-run:0.4.3
              variables:
                SSH_USER: $REMOTE_USER
                SERVER: $REMOTE_SERVER
                COMMAND: |
                  cd bitbucket-artifact-bw
                  unzip -o app.zip -d ../bezpiecznywypoczynek_new
                  cd ../bezpiecznywypoczynek_new
                  npm install --production --legacy-peer-deps
                  if ! command -v pm2 >/dev/null 2>&1; then
                    npm install -g pm2
                  fi
                  if pm2 list | grep -q "next-app"; then
                    pm2 restart next-app
                  else
                    pm2 start npm --name "next-app" -- start
                  fi

  default:
    - step:
        name: Build
        caches:
          - node
        script:
          - npm install --legacy-peer-deps
          - npm run build
