#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:18

pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - apt-get update && apt-get install -y zip
            - npm install --legacy-peer-deps
            - npm run build
            - zip -r out.zip out
          artifacts:
            - out.zip
      - step:
          name: Upload
          script:
              - mkdir artifact
              - cp out.zip artifact
              - pipe: atlassian/ftp-deploy:0.4.1
                variables:
                  USER: $REMOTE_USER
                  PASSWORD: $REMOTE_PASSWORD
                  SERVER: $REMOTE_SERVER
                  REMOTE_PATH: /bitbucket-artifact-bw/
                  LOCAL_PATH: ${BITBUCKET_CLONE_DIR}/artifact/
      - step:
          script:
              - pipe: atlassian/ssh-run:0.4.3
                variables:
                  SSH_USER: $REMOTE_USER
                  SERVER: $REMOTE_SERVER
                  COMMAND: 'unzip -o bitbucket-artifact-bw/out.zip && rm -r bezpiecznywypoczynek_new/* && cp -r out/* bezpiecznywypoczynek_new && rm -r bitbucket-artifact-bw && rm -r out && cd bezpiecznywypoczynek_new && nodecli restart'
  default:
    - step:
        name: Build
        caches:
          - node
        script:
          - npm install --legacy-peer-deps
          - npm run build